# Generated by Django 3.1.3 on 2020-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(default=None, max_length=255)),
                ('link', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
