# Generated by Django 3.1.3 on 2020-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialicons',
            old_name='loc',
            new_name='img_loc',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='bio',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
