# Generated by Django 3.1.3 on 2020-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201120_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('img_loc', models.CharField(default=None, max_length=255)),
                ('link', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialIcons',
        ),
    ]
