# Generated by Django 3.1.3 on 2020-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_contactresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
