# Generated by Django 3.1.3 on 2020-11-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20201120_0532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
